<?php

namespace AppBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
	public function loadRoleById($role)
    {
        return $this->createQueryBuilder('r')
            ->where('r.role = :role ')
            ->setParameter('role', $role)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
