AppBundle\Entity\Department:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DepartmentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        department:
            type: string
            length: '255'
            unique: true
    lifecycleCallbacks: {  }
